class_names = [
    {"name": "Banh canh (Vietnamese thick noodle soup)"},
    {"name": "Banh chung (Square sticky rice cake)"},
    {"name": "Banh cuon (Rolled rice pancake)"},
    {"name": "Banh khot (Mini savory pancakes)"},
    {"name": "Banh mi (Vietnamese baguette sandwich)"},
    {"name": "Banh trang (Rice paper)"},
    {"name": "Banh trang tron (Rice paper salad)"},
    {"name": "Banh xeo (Vietnamese sizzling pancake)"},
    {"name": "Bo kho (Beef stew)"},
    {"name": "Bo la lot (Grilled beef wrapped in betel leaves)"},
    {"name": "Bong cai (Cauliflower)"},
    {"name": "Bun (Rice vermicelli)"},
    {"name": "Bun bo Hue (Hue beef noodle soup)"},
    {"name": "Bun cha (Grilled pork with vermicelli)"},
    {"name": "Bun dau (Vermicelli with tofu)"},
    {"name": "Bun mam (Fermented fish noodle soup)"},
    {"name": "Bun rieu (Crab noodle soup)"},
    {"name": "Ca (Fish)"},
    {"name": "Ca chua (Tomato)"},
    {"name": "Ca phao (Pickled eggplant)"},
    {"name": "Ca rot (Carrot)"},
    {"name": "Canh (Soup)"},
    {"name": "Cha (Vietnamese pork roll)"},
    {"name": "Cha gio (Spring rolls)"},
    {"name": "Chanh (Lime)"},
    {"name": "Com (Rice)"},
    {"name": "Com tam (Broken rice)"},
    {"name": "Con nguoi (Human)"},
    {"name": "Cu kieu (Pickled scallion head)"},
    {"name": "Cua (Crab)"},
    {"name": "Dau hu (Tofu)"},
    {"name": "Dua chua (Pickled vegetables)"},
    {"name": "Dua leo (Cucumber)"},
    {"name": "Goi cuon (Fresh spring rolls)"},
    {"name": "Hamburger"},
    {"name": "Heo quay (Roast pork)"},
    {"name": "Hu tieu (Clear rice noodle soup)"},
    {"name": "Kho qua thit (Stuffed bitter melon soup)"},
    {"name": "Khoai tay chien (French fries)"},
    {"name": "Lau (Hotpot)"},
    {"name": "Long heo (Pork offal)"},
    {"name": "Mi (Egg noodles)"},
    {"name": "Muc (Squid)"},
    {"name": "Nam (Mushroom)"},
    {"name": "Oc (Snails)"},
    {"name": "Ot chuong (Bell pepper)"},
    {"name": "Pho (Vietnamese noodle soup)"},
    {"name": "Pho mai (Cheese)"},
    {"name": "Rau (Vegetables)"},
    {"name": "Salad (Salad)"},
    {"name": "Thit bo (Beef)"},
    {"name": "Thit ga (Chicken)"},
    {"name": "Thit heo (Pork)"},
    {"name": "Thit kho (Braised pork)"},
    {"name": "Thit nuong (Grilled meat)"},
    {"name": "Tom (Shrimp)"},
    {"name": "Trung (Egg)"},
    {"name": "Xoi (Sticky rice)"},
    {"name": "Banh beo (Vietnamese savory steamed rice cake)"},
    {"name": "Cao lau (Cao lau noodles)"},
    {"name": "Mi Quang (Quang-style noodles)"},
    {"name": "Com chien duong chau (Yangzhou fried rice)"},
    {"name": "Bun cha ca (Fish cake noodle soup)"},
    {"name": "Com chien ga (Fried rice with chicken)"},
    {"name": "Chao long (Pork organ congee)"},
    {"name": "Nom hoa chuoi (Banana blossom salad)"},
    {"name": "Nui xao bo (Stir-fried macaroni with beef)"},
    {"name": "Sup cua (Crab soup)"}
]
